### ISSUE TITLE
Add EXCLUDED_SOURCE_FILE_NAMES

### ISSUE THREAD

**Issue by segiddins** [samdmarshall/Xcode-Build-Settings-Reference#7]

**Comment by segiddins** [comment]
Hmm, it appears to be in the markdown file in this repo but not in http://pewpewthespells.com/blog/buildsettings.html

**Comment by samdmarshall** [comment]
:( i must not have updated it this after it got added, should be able to get to it this weekend.

**Comment by segiddins** [comment]
@samdmarshall can this be closed?

**Comment by samdmarshall** [comment]
gonna say yes, even though i have no idea if i actually did it or not, i've got something that will supersede it soon.
